# Generated by Django 5.0.3 on 2024-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('field_name_source', models.CharField(max_length=255)),
                ('field_name_target', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('BOOLEAN', 'Boolean'), ('EMAIL', 'Email'), ('URL', 'URL'), ('JSON', 'JSON'), ('CURRENCY', 'Currency'), ('PHONE_NUMBER', 'Phone Number'), ('POSTAL_CODE', 'Postal Code'), ('CSV', 'CSV'), ('BASE64', 'Base64 Encoded'), ('COLOR', 'Color')], max_length=25)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('formatted_name', models.CharField(blank=True, max_length=200)),
                ('transformation_rule', models.TextField(blank=True)),
                ('target_format', models.CharField(blank=True, max_length=255)),
                ('default_value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('currency_code', models.CharField(blank=True, max_length=10)),
                ('delimiter', models.CharField(blank=True, default=',', max_length=5)),
                ('color_format', models.CharField(blank=True, choices=[('HEX', 'HEX Code'), ('RGB', 'RGB Values')], max_length=10)),
            ],
            options={
                'unique_together': {('source', 'field_name_source')},
            },
        ),
    ]
