# Generated by Django 5.0.3 on 2024-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='data',
            field=models.CharField(default='defaultvalue', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default='defaultvalue', null=True, upload_to='uploads/'),
        ),
    ]
