# Generated by Django 5.0.3 on 2024-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(null=True)),
                ('content_type', models.CharField(max_length=255, null=True)),
                ('checksum', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('failed', 'Processing Failed')], default='uploaded', max_length=20)),
                ('processing_details', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
